/adapi/node/localization:
  ros__parameters:
    diagnostic_updater:
      period: 1.0
      use_fqn: true

/adapi/node/routing:
  ros__parameters:
    stop_check_duration: 1.0
    diagnostic_updater:
      period: 1.0
      use_fqn: true
